import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="grid grid-rows-[auto_1fr_auto] min-h-screen max-w-2xl mx-auto w-full">
          <header className="grid grid-cols-[auto_1fr_auto]">
            <div className="col-start-1">A|A</div>
            <nav className="col-start-3">Menu</nav>
          </header>
          <main className="">{children}</main>
          <footer className="grid grid-cols-[auto_1fr_auto] text-xs">
            <div className="col-start-1">2026</div>
            <div className="col-start-3">Bülent ALA</div>
          </footer>
        </div>
      </body>
    </html>
  );
}
