import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

const JetBrainsMono = JetBrains_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// COMPONENTS BEGIN
// const Header = () => {
//   return <div className='mx-auto max-w-3xl border border-red-500 '>HEADER</div>;
// };
// const Footer = () => {
//   return <div className='mx-auto max-w-3xl border border-red-500'>FOOTER</div>;
// };
// COMPONENTS END
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={JetBrainsMono.className}>
        <div className='grid grid-rows-[_auto_1fr_auto] max-w-3xl mx-auto min-h-screen'>
          <div className='border border-red-500 h-16 flex items-center '>
            HEADER
          </div>
          <main className='border border-red-500'>{children}</main>
          <div className='border border-red-500 h-16 flex items-center'>
            FOOTER
          </div>
        </div>
      </body>
    </html>
  );
}
